// Copyright 2026 Kroonen AI. SPDX-License-Identifier: Apache-2.0
import { build } from 'esbuild';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const directory = path.dirname(fileURLToPath(import.meta.url));
await mkdir(path.join(directory, 'vendor'), { recursive: true });
await build({
  absWorkingDir: directory,
  stdin: {
    contents: "export * from '@deepseek-ai/cordis';",
    resolveDir: directory,
    sourcefile: 'cordis-entry.mjs',
  },
  outfile: path.join(directory, 'vendor/cordis.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  minify: false,
  sourcemap: false,
  legalComments: 'inline',
  banner: { js: '// Generated by node build.mjs. Cordis 4.0.2 and Cosmokit 1.8.3; see THIRD_PARTY_NOTICES.md.' },
});
for (const [packageName, target] of [
  ['@deepseek-ai/cordis', 'CORDIS-LICENSE'],
  ['@deepseek-ai/cosmokit', 'COSMOKIT-LICENSE'],
]) {
  const license = await readFile(path.join(directory, 'node_modules', packageName, 'LICENSE'));
  await writeFile(path.join(directory, 'vendor', target), license);
}
